# Create electrons with momenta drawn from a uniform distribution

/edep/random/timeRandomSeed

# set edep
/edep/db/set/saveAllPrimTraj true
/edep/db/set/lengthThreshold 0.5 mm
/edep/db/set/trajectoryAccuracy 0.5 mm
/edep/db/set/neutronThreshold 10 MeV
/edep/db/set/gammaThreshold 5.0 MeV
/edep/hitLength LArD 0.5 mm
/edep/hitLength drift 0.5 mm
/edep/hitLength cryo 0.5 mm
/edep/phys/allCuts 0.5 mm
/edep/update

# Set generator
# /gps/particle e-
/gps/particle proton

## Custom Momentum generator 
# /gps/particle proton
/gps/position 0.0 0.0 0.0 cm
/gps/ene/type Mono
/gps/ene/mono 89.82 MeV # kinetic energy = sqrt(px**2 + py**2 + pz**2 + mass**2) - mass
/gps/direction -249.1 -126.4 314.0

## Uniform energy & isotropic angle 
# /gps/ene/type Lin
# /gps/ene/min 100 MeV
# /gps/ene/max 500 MeV
# /gps/ene/gradient 0.0
# /gps/ene/intercept 1.0
# /gps/ang/type iso


# /control/verbose 1
# /run/verbose 1
#/tracking/verbose 1
# /event/verbose 1

/run/initialize

# Turn off optical processes
/process/inactivate Cerenkov

#/run/beamOn 1
